package me.raunakagarwal.routeforge.exception;

public enum ErrorCode {
    SOURCE_ALREADY_EXISTS,
    ROUTE_ALREADY_EXISTS,
    SOURCE_NOT_FOUND,
    ROUTE_NOT_FOUND,
    ARGUMENT_NOT_VALID,
    SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    SERVICE_ERROR,
    SERVICE_ERROR_NOT_FOUND,
    SERVICE_ERROR_BAD_REQUEST
}